### ISSUE TITLE
Bug with one sentence documents 

### ISSUE THREAD

**Issue by Christian-Nja** [arne-cl/feng-hirst-rst-parser#3]
https://github.com/arne-cl/feng-hirst-rst-parser/blob/8f3121ca32faacb75ba21793b4117ab76e3ee26a/src/parse.py#L220-L223

I think i found a little bug here with one sentence documents that's the output i get.

file:
prova.txt

> questo file di prova.

sorry for italian, it means: "this a test file" 

command:
`python parse.py prova.txt
`

i get this ouput. I already insert inside the code a print to show that with one sentence doc the tree
is treat as list
```

Added classifier classifier1 to segmenter gCRF
Added feature writer to treebuilder
Added classifier bin1 to treebuilder gCRF
Added classifier mc1 to treebuilder gCRF
Added classifier bin2 to treebuilder gCRF
Added classifier mc2 to treebuilder gCRF
Finished initialization in 1.36 seconds.

Processing 1 documents, skipping 0
Parsing /home/linux/Tesi/rst-tool/feng-hirst-rst-parser/texts/prova.txt, progress: 0.00 (0 out of 1)
Processing sentence 0 out of 1
Finished preprocessing in 0.35 seconds.

Finished segmentation in 0.01 seconds.
Segmented into 1 EDUs.

Finished tree building.
Finished tree building in 0.00 seconds.
[ParseTree('n/a', [['questo', 'file', 'di', 'prova', '.', '<P>']])]
<type 'list'>
Traceback (most recent call last):
  File "parse.py", line 225, in parse
    pt.__setitem__(pt.leaf_treeposition(i), '_!%s!_' % edu_str) # parse tree with escape symbols
AttributeError: 'list' object has no attribute 'leaf_treeposition'
None
Some error occurred, skipping the file
Successfully unloaded syntax parser
Successfully unloaded gCRF
Successfully unloaded gCRF_intra_bin
Successfully unloaded gCRF_intra_mc
Successfully unloaded gCRF_multi_bin
Successfully unloaded gCRF_multi_mc
Traceback (most recent call last):
  File "parse.py", line 314, in main
    raise e
AttributeError: 'list' object has no attribute 'leaf_treeposition'
Traceback (most recent call last):
  File "parse.py", line 362, in <module>
    main(options, args)
  File "parse.py", line 323, in main
    raise Exception, traceback.print_exc()
Exception
```

**Comment by arne-cl** [comment]
I can reproduce the error for short English texts (that do not contain
a rhetorical relation) as well. What kind of _useful_ output would you expect in this case?

```
$ docker build -t feng-hirst .
$ cat /tmp/test.txt 
This is a test.
```

```
$ docker run -v /tmp:/tmp -ti feng-hirst /tmp/test.txt
Traceback (most recent call last):
  File "/opt/feng-hirst-rst-parser/src/parse.py", line 222, in parse
    pt.__setitem__(pt.leaf_treeposition(i), '_!%s!_' % edu_str) # parse tree with escape symbols
AttributeError: 'list' object has no attribute 'leaf_treeposition'
Traceback (most recent call last):
  File "/opt/feng-hirst-rst-parser/src/parse.py", line 311, in main
    raise e
AttributeError: 'list' object has no attribute 'leaf_treeposition'
Traceback (most recent call last):
  File "/opt/feng-hirst-rst-parser/src/parser_wrapper.py", line 72, in <module>
    main()
  File "/opt/feng-hirst-rst-parser/src/parser_wrapper.py", line 57, in main
    results = feng_main(options, args)
  File "/opt/feng-hirst-rst-parser/src/parse.py", line 320, in main
    raise Exception, traceback.print_exc()
Exception
```

**Comment by ccolonna** [comment]
Thank you arne for your response. Yeah obviously that's not a document but a single sentence text. I struggle for a little with that error before understand it was due to text length. I think maybe can be useful throw a warn to alert the user the text didn't have an rst analysis. Maybe something like: `"rst-parser can't parse a single edu text, it hasn't an rst structure. At least two edus are needed for a relation" `what do you think?

**Comment by arne-cl** [comment]
That would be an option, feel free to make the changes and open a pull request.
